{{- range .Values.Deployments }}
{{- $fullName := printf "%s-%s" $.Release.Name .name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $fullName }}
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: {{ $fullName }}
  type: ClusterIP
---
{{- end }}