directive @shareable on FIELD_DEFINITION | OBJECT

directive @link(url: String!, import: [link__Import]) on SCHEMA

directive @inaccessible on FIELD_DEFINITION | OBJECT | INTERFACE | UNION | ARGUMENT_DEFINITION | SCALAR | ENUM | ENUM_VALUE | INPUT_OBJECT | INPUT_FIELD_DEFINITION

directive @override(from: String!) on FIELD_DEFINITION

type Shopper
  @extends
  @key(fields: "id")
{
  id: ID! @external
}

type Order {
  """Identifier"""
  id: ID!

  """Id of the Shopper purchasing the order."""
  shopperId: String!
  shopper: Shopper!

  """Id of the product being purchased."""
  productId: String!

  """The amount of products being purchased."""
  quantity: Float!

  """The total amount the shopper will be charged for the order."""
  totalPrice: Float!
}

type Query {
  orders: [Order!]!
  order(id: String!): Order!
}

type Mutation {
  createOrder(createOrderInput: CreateOrderInput!): Order!
  updateOrder(updateOrderInput: UpdateOrderInput!): Order!
  removeOrder(id: String!): Order!
}

input CreateOrderInput {
  """Id of the Shopper purchasing the order."""
  shopperId: String!

  """Id of the product being purchased."""
  productId: String!

  """The amount of products being purchased."""
  quantity: Float!

  """The total amount the shopper will be charged for the order."""
  totalPrice: Float!
}

input UpdateOrderInput {
  """Id of the Shopper purchasing the order."""
  shopperId: String

  """Id of the product being purchased."""
  productId: String

  """The amount of products being purchased."""
  quantity: Float

  """The total amount the shopper will be charged for the order."""
  totalPrice: Float

  """Identifier"""
  id: ID!
}

scalar link__Import